module.exports = {
  USER_ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    COUNSELLOR: 'COUNSELLOR',
    ADVISOR: 'ADVISOR',
    OPERATION: 'OPERATION',
    COLLECTION: 'COLLECTION',
    LEGAL: 'LEGAL'
  },
  
  LOAN_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    DISBURSED: 'DISBURSED',
    ACTIVE: 'ACTIVE',
    CLOSED: 'CLOSED',
    DEFAULTED: 'DEFAULTED',
    LEGAL: 'LEGAL'
  },
  
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    OVERDUE: 'OVERDUE'
  },
  
  PAYMENT_MODES: {
    CASH: 'CASH',
    CHEQUE: 'CHEQUE',
    BANK_TRANSFER: 'BANK_TRANSFER',
    UPI: 'UPI',
    CARD: 'CARD'
  },
  
  FREQUENCY: {
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY'
  }
};